#!/usr/bin/env python3
"""Initialize a persistent workspace for the wind farm topic workflow."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EVIDENCE_STATUSES = [
    "verified",
    "user_provided",
    "inferred",
    "needs_literature_verification",
    "speculative",
]


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_manifest() -> dict:
    return json.loads((ROOT / "skill_manifest.json").read_text())


def safe_project_id(project_id: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", project_id):
        raise SystemExit(f"invalid project_id: {project_id!r}")
    if ".." in project_id:
        raise SystemExit(f"invalid project_id contains '..': {project_id!r}")
    return project_id


def parse_simple_yaml(text: str) -> dict:
    data: dict[str, object] = {}
    current_key: str | None = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if not line.startswith(" ") and ":" in line:
            key, value = line.split(":", 1)
            key = key.strip()
            value = value.strip()
            current_key = key
            if value:
                data[key] = value.strip("\"'")
            else:
                data[key] = []
        elif current_key and line.startswith("  - "):
            if not isinstance(data[current_key], list):
                raise ValueError(f"fallback YAML parser cannot parse mixed scalar/list key: {current_key}")
            data[current_key].append(line[4:].strip().strip("\"'"))
        elif current_key and line.startswith("  ") and ":" in line:
            if data[current_key] == []:
                data[current_key] = {}
            if not isinstance(data[current_key], dict):
                raise ValueError(f"fallback YAML parser cannot parse nested key under list: {current_key}")
            key, value = line.strip().split(":", 1)
            data[current_key][key.strip()] = value.strip().strip("\"'")
        else:
            raise ValueError(f"fallback YAML parser cannot parse line: {raw}")
    return data


def load_yaml(path: Path) -> tuple[dict, str]:
    text = path.read_text()
    try:
        import yaml  # type: ignore

        loaded = yaml.safe_load(text)
        if not isinstance(loaded, dict):
            raise SystemExit(f"YAML root must be a mapping: {path}")
        return loaded, "pyyaml"
    except ImportError:
        try:
            return parse_simple_yaml(text), "fallback"
        except ValueError as exc:
            raise SystemExit(f"PyYAML not installed and fallback parser cannot parse this YAML: {exc}") from exc


def evidence_policy() -> dict:
    return {
        "default_literature_status": "needs_literature_verification",
        "allowed_statuses": EVIDENCE_STATUSES,
    }


def trace_context(source_modules: list[str] | None = None) -> dict:
    return {
        "source_module_ids": source_modules or [],
        "domain_tension_ids": [],
        "problem_ids": [],
        "theory_element_ids": [],
        "contribution_ids": [],
        "lineage": [],
    }


def evidence_item(statement: str, status: str = "speculative", source: str = "workspace initialization") -> dict:
    return {"statement": statement, "evidence_status": status, "source": source}


def global_fields(project_id: str, module_id: str, module_name: str, upstream: str | None) -> dict:
    return {
        "schema_version": "1.0",
        "project_id": project_id,
        "status": "draft",
        "module_id": module_id,
        "module_name": module_name,
        "input_summary": {
            "direct_upstream_module_id": upstream,
            "summary": "Draft placeholder generated by init_workspace.py.",
            "consumed_files": [],
        },
        "assumptions": [evidence_item("This draft placeholder must be replaced by a module run.", "speculative")],
        "uncertainty_log": [
            {
                "item": "Module output has not been generated yet.",
                "evidence_status": "speculative",
                "action_required": "Run or manually complete this module before treating it as evidence.",
            }
        ],
        "evidence_requirements": [
            {
                "requirement_id": f"er_{module_id}",
                "requirement": "Replace placeholder with evidence-bounded module output.",
                "evidence_status": "speculative",
            }
        ],
        "reviewer_risks": [
            {
                "risk_id": f"rr_{module_id}",
                "question": "Is this placeholder being mistaken for validated research content?",
                "mitigation": "Keep status as draft until real module content is supplied.",
                "evidence_status": "speculative",
            }
        ],
        "revision_hooks": [
            {
                "field": "structured_output",
                "action": "Replace placeholder fields with module-specific evidence-bounded content.",
                "affects": [module_id],
            }
        ],
        "trace_context": trace_context([module_id]),
    }


def module_skeleton(project_id: str, module_id: str, module_name: str, upstream: str | None, project_input: dict) -> dict:
    output = global_fields(project_id, module_id, module_name, upstream)
    if module_id == "00_project_intake":
        scope = project_input.get("research_scope", [])
        preferred = project_input.get("preferred_methods", [])
        avoided = project_input.get("avoided_directions", [])
        constraints = project_input.get("constraints", [])
        output["structured_output"] = {
            "researcher_profile": project_input.get("researcher_profile", {}),
            "research_scope": [evidence_item(str(item), "user_provided", "input YAML") for item in scope],
            "target_output": str(project_input.get("target_output", "research topic package")),
            "known_constraints": [evidence_item(str(item), "user_provided", "input YAML") for item in constraints],
            "preferred_methods": [evidence_item(str(item), "user_provided", "input YAML") for item in preferred],
            "avoided_directions": [evidence_item(str(item), "user_provided", "input YAML") for item in avoided],
            "expected_contribution_types": [evidence_item("modeling, algorithmic, and experimental planning contributions require downstream evidence.", "inferred")],
            "available_resources": [evidence_item("Available code, datasets, and literature library require user confirmation.", "speculative")],
            "uncertainty_log": output["uncertainty_log"],
        }
        output["next_input"] = {
            "project_id": project_id,
            "research_scope": scope if isinstance(scope, list) else [str(scope)],
            "domain_keywords": ["wind farm layout optimization", "wind farm cable routing optimization", "joint layout-cabling optimization", "evolutionary computation"],
            "inclusion_boundary": ["optimization problem structure", "layout-cabling coupling", "multi-objective constrained optimization"],
            "exclusion_boundary": avoided if isinstance(avoided, list) else [str(avoided)],
            "preferred_methods": preferred if isinstance(preferred, list) else [str(preferred)],
            "target_output": "research topic package",
            "evidence_policy": evidence_policy(),
            "trace_context": trace_context([module_id]),
        }
        return output
    if module_id == "01_domain_scan":
        output["structured_output"] = {
            "domain_boundaries": {},
            "research_streams": [],
            "method_problem_matrix": [],
            "objective_constraint_map": [],
            "coupling_map": [],
            "domain_tensions": [],
            "saturated_areas": [],
            "active_areas": [],
            "underexplored_areas": [],
            "evidence_requirements": [],
            "uncertainty_log": [],
        }
        output["next_input"] = {
            "candidate_tensions": [],
            "domain_boundaries": {},
            "method_problem_matrix_summary": [],
            "objective_constraint_summary": [],
            "coupling_summary": [],
            "evidence_policy": evidence_policy(),
            "trace_context": trace_context([module_id]),
        }
    elif module_id == "02_problem_identification":
        card = {
            "problem_id": "PENDING_PROBLEM",
            "problem_title": "PENDING_MODULE_OUTPUT",
            "problem_statement": "PENDING_MODULE_OUTPUT",
            "source_domain_tension_id": "PENDING_DOMAIN_TENSION",
            "source_domain_tension": "PENDING_MODULE_OUTPUT",
            "problem_type": "PENDING_MODULE_OUTPUT",
            "why_it_matters": "PENDING_MODULE_OUTPUT",
            "why_not_solved_yet": "PENDING_MODULE_OUTPUT",
            "research_question": "PENDING_MODULE_OUTPUT",
            "evidence_needed": [],
            "expected_contribution_opportunities": [],
            "feasibility": "PENDING_MODULE_OUTPUT",
            "novelty_risk": "PENDING_MODULE_OUTPUT",
            "reviewer_risk": "PENDING_MODULE_OUTPUT",
            "publishability_score": 0,
            "scoring_breakdown": {},
            "next_input_fragment": {},
            "evidence_status": "speculative",
        }
        output["structured_output"] = {
            "candidate_problems": [card],
            "selected_problem": card,
            "backup_problems": [],
            "ranking_criteria": [],
            "rejected_problems": [],
            "selection_rationale": "PENDING_MODULE_OUTPUT",
            "evidence_requirements": [],
            "uncertainty_log": [],
        }
        output["next_input"] = {
            "selected_problem": {"problem_id": "PENDING_PROBLEM"},
            "backup_problems_summary": [],
            "problem_properties": [],
            "required_theoretical_positioning": [],
            "evidence_policy": evidence_policy(),
            "trace_context": trace_context([module_id]),
        }
    elif module_id == "03_theoretical_positioning":
        output["structured_output"] = {
            "problem_class": [],
            "formal_problem_elements": {
                "decision_space": "PENDING_MODULE_OUTPUT",
                "objective_space": "PENDING_MODULE_OUTPUT",
                "constraint_space": "PENDING_MODULE_OUTPUT",
                "coupling_structure": "PENDING_MODULE_OUTPUT",
                "evaluation_cost": "PENDING_MODULE_OUTPUT",
                "search_difficulty": "PENDING_MODULE_OUTPUT",
            },
            "decision_variables": [],
            "objective_functions": [],
            "constraints": [],
            "complexity_sources": [],
            "coupling_mechanisms": [],
            "method_implications": [],
            "theory_to_contribution_bridge": [],
            "evidence_requirements": [],
            "uncertainty_log": [],
        }
        output["next_input"] = {
            "selected_problem": {},
            "problem_class": [],
            "problem_properties": [],
            "method_implications": [],
            "theory_to_contribution_bridge": [],
            "contribution_design_targets": [],
            "evidence_policy": evidence_policy(),
            "trace_context": trace_context([module_id]),
        }
    elif module_id == "04_contribution_argumentation":
        output["structured_output"] = {
            "central_thesis": "PENDING_MODULE_OUTPUT",
            "contributions": [],
            "contribution_to_problem_links": [],
            "contribution_to_theory_links": [],
            "required_validation": [],
            "unsafe_claims_removed": [],
            "safer_wording_map": [],
            "evidence_requirements": [],
            "uncertainty_log": [],
        }
        output["next_input"] = {
            "central_thesis": "PENDING_MODULE_OUTPUT",
            "contributions": [],
            "contribution_links": [],
            "required_validation": [],
            "reviewer_risks": [],
            "evidence_policy": evidence_policy(),
            "trace_context": trace_context([module_id]),
        }
    elif module_id == "05_chain_consistency_audit":
        output["structured_output"] = {
            "chain_status": "revise_required",
            "broken_links": [],
            "weak_links": [],
            "overclaim_risks": [],
            "vague_claims": [],
            "missing_evidence": [],
            "missing_experiments": [],
            "missing_baselines": [],
            "missing_ablations": [],
            "reviewer_questions": [],
            "repair_actions": [],
            "pass_or_revise_decision": "PENDING_MODULE_OUTPUT",
            "final_package_readiness": "PENDING_MODULE_OUTPUT",
            "evidence_requirements": [],
            "uncertainty_log": [],
        }
        output["next_input"] = {
            "audited_central_thesis": "PENDING_MODULE_OUTPUT",
            "approved_contributions": [],
            "required_repairs": [],
            "validation_plan_requirements": [],
            "reviewer_risk_summary": [],
            "final_package_sections": [],
            "evidence_policy": evidence_policy(),
            "trace_context": trace_context([module_id]),
        }
    else:
        output["structured_output"] = {
            "candidate_title": "PENDING_MODULE_OUTPUT",
            "alternative_titles": [],
            "central_thesis": "PENDING_MODULE_OUTPUT",
            "research_background": "PENDING_MODULE_OUTPUT",
            "domain_gap": "PENDING_MODULE_OUTPUT",
            "core_problem": "PENDING_MODULE_OUTPUT",
            "theoretical_positioning": "PENDING_MODULE_OUTPUT",
            "research_questions": [],
            "contribution_claims": [],
            "method_design_implications": [],
            "validation_plan": [],
            "required_baselines": [],
            "required_ablation_studies": [],
            "reviewer_risk_and_defense": [],
            "introduction_logic_outline": [],
            "traceability_table": [],
            "next_research_actions": [],
            "evidence_requirements": [],
            "uncertainty_log": [],
        }
        output["next_input"] = {}
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path, help="YAML project input file")
    parser.add_argument("--project-id", required=True, help="Workspace project id")
    parser.add_argument("--root", default="workspaces", type=Path)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    project_id = safe_project_id(args.project_id)
    input_path = args.input if args.input.is_absolute() else ROOT / args.input
    project_input, parse_mode = load_yaml(input_path)

    workspace_root = args.root if args.root.is_absolute() else ROOT / args.root
    workspace = workspace_root / project_id
    if workspace.exists():
        if not args.overwrite:
            raise SystemExit(f"workspace already exists: {workspace}; pass --overwrite to replace it")
        shutil.rmtree(workspace)
    workspace.mkdir(parents=True)

    modules = load_manifest()["modules"]
    module_order = [m["workspace_id"] for m in modules]
    output_paths = {}

    for index, module in enumerate(modules):
        module_id = module["workspace_id"]
        module_name = module["module_doc"].split("/", 1)[1].removesuffix(".md").split("_", 1)[1].replace("_", " ").title()
        upstream = module_order[index - 1] if index else None
        module_dir = workspace / module_id
        module_dir.mkdir()
        input_content = project_input if index == 0 else {
            "status": "pending",
            "module_id": module_id,
            "source_module_id": upstream,
            "note": "Use resume_from_module.py to load direct upstream next_input.json.",
        }
        output = module_skeleton(project_id, module_id, module_name, upstream, project_input)
        files = {
            "input.json": input_content,
            "output.json": output,
            "next_input.json": output["next_input"],
        }
        for name, content in files.items():
            (module_dir / name).write_text(json.dumps(content, indent=2, ensure_ascii=False) + "\n")
        (module_dir / "output.md").write_text(f"# {module_name}\n\nDraft placeholder. Replace with module output.\n")
        (module_dir / "validation_report.md").write_text("# Validation Report\n\nStatus: NOT_RUN\n")
        output_paths[module_id] = {name: str(module_dir / name) for name in ["input.json", "output.json", "output.md", "next_input.json", "validation_report.md"]}

    state = {
        "project_id": project_id,
        "created_at": now(),
        "input_source": str(input_path),
        "input_parse_mode": parse_mode,
        "current_module": module_order[0],
        "completed_modules": [],
        "module_order": module_order,
        "module_output_paths": output_paths,
        "last_validated_module": None,
        "notes": ["Initialized workspace with draft placeholders."],
        "history": [
            {
                "timestamp": now(),
                "event": "init_workspace",
                "project_id": project_id,
                "input_source": str(input_path),
            }
        ],
    }
    (workspace / "project_state.json").write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n")
    print(f"PASS initialized workspace: {workspace}")


if __name__ == "__main__":
    main()
